services:

  neo4j:

    image: neo4j:5.26-community

    container_name: maintain-fee-service-graph

    restart: unless-stopped

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:

      NEO4J_AUTH: neo4j/password

      NEO4J_PLUGINS: '["apoc"]'

    volumes:

      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import